package sn.esmt.tasks.taskmanager.entities.enums;

public enum StatusUser {
	ACTIVE, SUSPENDED, INVITATION_PENDING, ACTIVATION_PENDING, INACTIVE, REMOVE, TOKEN_EXPIRED, PENDING_FROM_MAIL, PENDING_FROM_PHONE_CODE,
	NOT_REGISTERED
}
